# Generated by Django 3.2.5 on 2021-07-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_1', models.CharField(max_length=200)),
                ('matrix_2', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_text', models.CharField(max_length=200)),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compute.computation')),
            ],
        ),
    ]
