# Generated by Django 3.2.5 on 2021-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SVRmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_addr', models.CharField(max_length=200)),
                ('fund_addr', models.CharField(max_length=200)),
                ('mse', models.CharField(max_length=200)),
                ('mae', models.CharField(max_length=200)),
            ],
        ),
    ]
